# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhoneVerification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhoneVerification
    pod 'Moya', '~> 11.0'

  target 'PhoneVerificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhoneVerificationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
